#!/bin/bash
# Explicit delivery operation: signs an iOS or Mac archive at export and uploads it to App Store Connect for
# TestFlight. Uses the App Store Connect API key named by ASC_API_KEY_PATH, ASC_API_KEY_ID and ASC_API_ISSUER_ID.
set -euo pipefail
cd "$(dirname "$0")/.."
archive="${1:?Usage: upload-app-store.sh <My Journal.xcarchive> <ExportOptions.plist> <new-output-directory>}"
options="${2:?Provide upload export options generated by prepare-app-store-export.py}"
output="${3:?Choose a new output directory}"
: "${ASC_API_KEY_PATH:?}" "${ASC_API_KEY_ID:?}" "${ASC_API_ISSUER_ID:?}"
[[ -d "$archive/Products/Applications/My Journal.app" && -f "$options" && -f "$ASC_API_KEY_PATH" && ! -e "$output" ]] || {
  echo "A My Journal archive, upload options, API key file, and new output directory are required." >&2
  exit 2
}
python3 - "$options" <<'PY'
import plistlib
import sys
with open(sys.argv[1], "rb") as source:
    options = plistlib.load(source)
if options.get("destination") != "upload" or options.get("method") != "app-store-connect":
    raise SystemExit("Upload options must use the app-store-connect method and the upload destination.")
if not options.get("teamID"):
    raise SystemExit("A development team ID is required.")
PY
mkdir -p "$output"
output="$(cd "$output" && pwd)"
xcodebuild -exportArchive -archivePath "$archive" -exportOptionsPlist "$options" -exportPath "$output" \
  -allowProvisioningUpdates -authenticationKeyPath "$ASC_API_KEY_PATH" \
  -authenticationKeyID "$ASC_API_KEY_ID" -authenticationKeyIssuerID "$ASC_API_ISSUER_ID"
printf 'Uploaded to App Store Connect; the build appears in TestFlight after processing.\n'
